module.exports = {
    common_01: '方法不支持',
    group_01: '用户组已存在',
    group_02: '用户组不存在',
    group_02: '叶子节点没有路径',
    group_03: '用户组下存在用户',
    usersetting_01: '密码错误',
    usersetting_02: '用户不存在',
    operator_01: '组不存在',
    operator_02: '用户已经存在',
    operator_03: '用户不存在',
    menu_01: '菜单已经存在',
    menu_02: '菜单不存在',
    menu_03: '菜单下有子项',
    auth_01: 'domain is missing',
    auth_02: 'username is missing',
    auth_03: 'identifyCode is missing',
    auth_04: 'magicNo is missing',
    auth_05: '用户不存在或密码错误'
};
