#!/bin/sh
rm -rf store;cp -rf ../../../node_modules/store store
rm -rf bootstrap;cp -rf ../../../node_modules/bootstrap bootstrap
rm -rf select2;cp -rf ../../../node_modules/select2 select2
rm -rf font-awesome;cp -rf ../../../node_modules/font-awesome font-awesome
rm -rf bootstrap-table;cp -rf ../../../node_modules/bootstrap-table bootstrap-table
rm -rf bootstrap-datepicker;cp -rf ../../../node_modules/bootstrap-datepicker bootstrap-datepicker
rm -rf bootstrap-daterangepicker;cp -rf ../../../node_modules/bootstrap-daterangepicker bootstrap-daterangepicker
rm -rf lightbox2;cp -rf ../../../node_modules/lightbox2 lightbox2
rm -rf jquery-slimscroll;cp -rf ../../../node_modules/jquery-slimscroll jquery-slimscroll
rm -rf x-editable;cp -rf ../../../node_modules/x-editable x-editable
rm -rf jquery-sparkline;cp -rf ../../../node_modules/jquery-sparkline jquery-sparkline
rm -rf fastclick;cp -rf ../../../node_modules/fastclick fastclick
rm -rf raphael;cp -rf ../../../node_modules/raphael raphael
rm -rf moment;cp -rf ../../../node_modules/moment moment
rm -rf tableexport.jquery.plugin;cp -rf ../../../node_modules/tableexport.jquery.plugin tableexport.jquery.plugin
rm -rf cropper;cp -rf ../../../node_modules/cropper cropper
rm -rf crypto-js;cp -rf ../../../node_modules/crypto-js crypto-js
rm -rf ckeditor;cp -rf ../../../node_modules/ckeditor ckeditor
rm -rf ztree;cp -rf ../../../node_modules/ztree ztree
rm -rf parsleyjs;cp -rf ../../../node_modules/parsleyjs parsleyjs
